<?php
namespace Encounting\Jcdh;

use Encounting\Jcdh\Models\JcdhCommunalLiving;
use Encounting\Jcdh\Models\JcdhDeduction;
use Encounting\Jcdh\Models\JcdhFood;
use Encounting\Jcdh\Models\JcdhHotel;
use Encounting\Jcdh\Models\JcdhPool;
use Encounting\Jcdh\Models\JcdhTanning;

use SimpleXMLElement;

/**
 * I belong to a class
 */
class JcdhApi {
    const REQUEST_FAIL = 'REQUEST_NOT_PROCESSED';
    const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

    const TYPE_COMMUNAL_LIVING = 'communal';
    const TYPE_FOOD = 'food';
    const TYPE_HOTEL = 'hotel';
    const TYPE_POOL = 'pool';
    const TYPE_TANNING = 'tanning';

    const OUTPUT_JSON = 'json';
    const OUTPUT_XML = 'xml';

    const URL_COMMUNAL_LIVING_SCORES = 'https://webapps.jcdh.org/scores/ehcl/communallivingscores.aspx';
    const URL_FOOD_SCORES = 'https://webapps.jcdh.org/scores/ehfs/foodservicescores.aspx';
    const URL_HOTEL_SCORES = 'https://webapps.jcdh.org/scores/ehhls/hotellodgingscores.aspx';
    const URL_POOL_SCORES = 'https://webapps.jcdh.org/scores/ehps/poolscores.aspx';
    const URL_TANNING_SCORES = 'https://webapps.jcdh.org/scores/ehts/tanningscores.aspx';

    const URL_GOOGLE_GEOCODE = 'https://maps.google.com/maps/api/geocode/json';

    private $_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    private $_errors = false;

    private $_useJson = false;
    private $_useXml = false;

    /**
     * JcdhApi constructor.
     *
     * @param string|false $use  Return results in a specific format; options 'json', 'xml', or false for a stdClass
     *
     * @return void
     */
    public function __construct($use = false) {
        $this->_setUse($use);
    }

    private function _buildUrl($base, $letter) {
        $url = $base;
        if (is_string($letter)) {
            $url .= '?Letter='.$letter;
        }

        return $url;
    }

    /**
     * Remove all errors
     *
     * @return void
     */
    private function _clearErrors() {
        $this->_setErrors(false);
    }

    private function _getLatLng($address) {
        $prepAddr = str_replace(' ', '+', $address);
        $geocode = file_get_contents(self::URL_GOOGLE_GEOCODE.'?address=' . $prepAddr . '&sensor=false&key=');
        $output = json_decode($geocode);

        return $output->results[0]->geometry->location;
    }

    private function _getPageCount($html, $typeId) {
        $pages = [];

        $tr = end($html->find('#'.$typeId.' tr'));
        foreach ($tr->children as $td) {
            $page = trim($td->plaintext);

            if (is_numeric($page)) {
                $page = intval($page, 10);

                $pages[] = $page;
            }
        }

        if (count($pages) === 0) {
            $pages[] = 1;
        }

        return $pages;
    }

    private function getCommunalLivingScores() {
        $html = $this->_request(
            self::URL_COMMUNAL_LIVING_SCORES
        );

        $scores = [];
        foreach($html->find('tr') as $id => $tr) {
            $tds = $tr->children;

            if (count($tds) === 3 && $tds[0]->plaintext !== 'Score') {
                $communal = new JcdhCommunalLiving();

                $communal->score = $tds[0]->plaintext;

                $nameAndAddress = $this->_splitNameAddress($tds[1]->plaintext);
                $communal->name = trim($nameAndAddress[0]);
                $communal->address = trim($nameAndAddress[1]);

//                TODO:
//                $business->location = _getLatLng($business->address);

                $communal->date = $tds[2]->plaintext;

                $scores[] = $communal;
            }
        }

        return $scores;
    }

    /**
     * Get an array of food scores, all of the letter passed in or the most recent if $letter is false
     *
     * @param string|bool $letter
     *
     * @return JcdhFood[]
     */
    private function getFoodScores($letter = false) {
        $url = $this->_buildUrl(self::URL_FOOD_SCORES, $letter);

        $page = 0;
        $pageCount = 0;

        $scores = [];

        do {
            $html = $this->_request($url, ++$page);

            if ($pageCount === 0) {
                $pageCount = $this->_getPageCount($html, 'MainContent_gvFoodScores');
            }

            foreach ($html->find('tr') as $id => $tr) {
                $tds = $tr->children;

                if (count($tds) === 5 && $tds[0]->plaintext !== 'PermitNbr') {
                    $food = new JcdhFood();

                    $food->permit_no = $tds[0]->plaintext;
                    $food->score = $tds[1]->plaintext;

                    $nameAndAddress = $this->_splitNameAddress($tds[2]->plaintext);
                    $food->name = trim($nameAndAddress[0]);
                    $food->address = trim($nameAndAddress[1]);

//                TODO:
//                $business->location = _getLatLng($business->address);

                    $food->date = $tds[3]->plaintext;

                    $food->smoke_free = $tds[4] === 'Y';

                    $food->deductions = null;

                    $scores[] = $food;
                }
            }
        } while ($page <= $pageCount);

        return $scores;
    }

    private function getHotelScores() {
        $html = $this->_request(
            self::URL_HOTEL_SCORES
        );

        $scores = [];
        foreach($html->find('tr') as $id => $tr) {
            $tds = $tr->children;
            if (count($tds) === 5 && $tds[0]->plaintext !== 'EstabNbr') {
                $hotel = new JcdhHotel();

                $hotel->establishment_number = $tds[0]->plaintext;

                $hotel->score = $tds[1]->plaintext;

                $nameAndAddress = $this->_splitNameAddress($tds[2]->plaintext);
                $hotel->name = trim($nameAndAddress[0]);
                $hotel->address = trim($nameAndAddress[1]);

//                TODO
//                $business->location = getLatLng($business->address);

                $hotel->date = $tds[3]->plaintext;

                $hotel->number_of_units = $tds[4]->plaintext;

                $scores[] = $hotel;
            }
        }

        return $scores;
    }

    private function getPoolScores() {
        $html = $this->_request(
            self::URL_POOL_SCORES
        );

        $scores = [];
        foreach($html->find('tr') as $id => $tr) {
            $tds = $tr->children;
            if (count($tds) === 4 && $tds[0]->plaintext !== 'Score') {
                $business = new JcdhPool();

                $business->score = $tds[0]->plaintext;

                $business->type = $tds[1]->plaintext;

                $nameAndAddress = $this->_splitNameAddress($tds[2]->plaintext);
                $business->name = trim($nameAndAddress[0]);
                $business->address = trim($nameAndAddress[1]);

//                TODO
//                $business->location = getLatLng($business->address);

                $business->date = $tds[3]->plaintext;

                $scores[] = $business;
            }
        }

        return $scores;
    }

    private function getTanningScores() {
        $html = $this->_request(
            self::URL_TANNING_SCORES
        );

        $scores = [];
        foreach($html->find('tr') as $id => $tr) {
            $tds = $tr->children;
            if (count($tds) === 4 && $tds[0]->plaintext !== 'PermitNbr') {
                $business = new JcdhTanning();

                $business->permit_no = $tds[0]->plaintext;
                $business->score = $tds[1]->plaintext;

                $nameAndAddress = preg_split('/\n|\r\n?/', $tds[2]->plaintext);
                $business->name = trim($nameAndAddress[0]);
                $business->address = trim($nameAndAddress[1]);

//                TODO
//                $business->location = getLatLng($business->address);

                $business->date = $tds[3]->plaintext;

                $scores[] = $business;
            }
        }

        return $scores;
    }

    private function _getFoodReport($permitNo) {
        // TODO: Refactor and make work
        $deductions = [];

        $content = file_get_contents('https://webapps.jcdh.org/scores/ehfs/FSSDetails.aspx?PermitNbr='.$permitNo.'&InspNbr=13');

        $html = str_get_html($content);

        $deductionTable = $html->find('#MainContent_TabContainer1_TabPanel1_Score1Ctrl1_GVScoreDetails');
        if (is_array($deductionTable) && count($deductionTable) > 0) {
            $deductionTable = $deductionTable[0];

            foreach ($deductionTable->children as $tr) {
                $tds = $tr->find('td');

                if (is_array($tds) && count($tds) > 0) {
                    $deduction = new JcdhDeduction();
                    $deduction->value = $tds[0]->plaintext;

                    $notes = $tds[1]->plaintext;

                    $codeRegex = '[0-9]{1}-[0-9]+.[0-9]+(\([A-Z]\))*';
                    $codeBeforeParenthesis = '\s[0-9]{1}-[0-9]+.[0-9]+(\([A-Z]\))*\s([A-Za-z0-9]|\s)+';
                    $codeParenthesis = '';
                    $codeAfterParenthesis = '[A-Za-z0-9]*\.';
                    $afterPeriodParenthesis = '(\s\((.*)\))*';

                    $regex = $codeRegex.$codeBeforeParenthesis.$codeParenthesis.$codeAfterParenthesis.$afterPeriodParenthesis;

                    $notes = preg_split('/'.$codeRegex.'/', $notes);
                    foreach ($notes as $note) {

                    }

                    $deductions[] = $deduction;
                }
            }
        } else {
            error_log('Unable to find the deduction table.');
        }

        return $deductions;
    }

    private function _getLetters() {
        return str_split($this->_LETTERS);
    }

    private function _processResults($results) {
        if ($this->_useJson) {
            $results = json_encode($results);
        } else if ($this->_useXml) {
            $xml = new SimpleXMLElement('<root/>');

            array_walk_recursive(
                json_decode(json_encode($results), true),
                [
                    $xml,
                    'addChild'
                ]
            );

            $results = $xml->asXML();
        }

        return $results;
    }

    private function _request($url, $page = 1) {
        $context = null;

        if ($page !== 1) {
            $opts = [
                'http' => [
                    'method'  => 'POST',
                    'header'  => 'Content-type: application/x-www-form-urlencoded',
                    'content' => http_build_query(
                        [
                            '__EVENTTARGET'        => 'ctl00$MainContent$gvFoodScores',
                            '__EVENTARGUMENT'      => 'Page$'.$page,
                            '__VIEWSTATE'          => '/wEPDwUJOTc5Nzk0ODI5D2QWAmYPZBYCAgMPZBYCAgUPZBYCAkEPPCsAEQMADxYEHgtfIURhdGFCb3VuZGceC18hSXRlbUNvdW50AqsBZAEQFgAWABYADBQrAAAWAmYPZBbKAQIBD2QWCmYPDxYCHgRUZXh0BQUxNTAzNGRkAgEPZBYCZg8PFgQfAgUCOTgeC05hdmlnYXRlVXJsBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNTAzNCZJbnNwTmJyPTI2ZGQCAg9kFgQCAQ8PFgIfAgUZQSAmIFQgRk9PRCBNQVJUIChDSEVWUk9OKWRkAgMPDxYCHwIFHTE2IDY0VEggU1QgTiBCSVJNSU5HSEFNIDM1MjEyZGQCAw8PFgIfAgUJNS8xOC8yMDE4ZGQCBA8PFgIfAgUBWWRkAgIPZBYKZg8PFgIfAgUFMTcxNzVkZAIBD2QWAmYPDxYEHwIFAjk0HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE3MTc1Jkluc3BOYnI9NTlkZAICD2QWBAIBDw8WAh8CBRVBIEJFQVVUSUZVTCBCRUdJTk5JTkdkZAIDDw8WAh8CBR0xNDA2IDI3VEggU1QgTiBCRVNTRU1FUiAzNTAyMGRkAgMPDxYCHwIFCTQvMTAvMjAxOGRkAgQPDxYCHwIFAVlkZAIDD2QWCmYPDxYCHwIFBTIxNjE0ZGQCAQ9kFgJmDw8WBB8CBQI5OR8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMTYxNCZJbnNwTmJyPTlkZAICD2QWBAIBDw8WAh8CBRJBIERFQVIgREFZQ0FSRSBJTkNkZAIDDw8WAh8CBSIxNDI4IEhFRkxJTiBBVkUgVyBCSVJNSU5HSEFNIDM1MjE0ZGQCAw8PFgIfAgUJNC8xMi8yMDE4ZGQCBA8PFgIfAgUBWWRkAgQPZBYKZg8PFgIfAgUEMTk4M2RkAgEPZBYCZg8PFgQfAgUCOTEfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTk4MyZJbnNwTmJyPTQ4ZGQCAg9kFgQCAQ8PFgIfAgUdQSBTT0NJQUwgQUZGQUlSL0dPVVJNRVQgVE8gR09kZAIDDw8WAh8CBRsxMjcgT0FLIFNUIEJJUk1JTkdIQU0gMzUyMTNkZAIDDw8WAh8CBQk2LzEyLzIwMThkZAIEDw8WAh8CBQFZZGQCBQ9kFgpmDw8WAh8CBQUxNDUwN2RkAgEPZBYCZg8PFgQfAgUCOTEfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTQ1MDcmSW5zcE5icj0xNGRkAgIPZBYEAgEPDxYCHwIFEEEgVE8gWiBGT09EIE1BUlRkZAIDDw8WAh8CBSgyMDMxIE9MRCBTUFJJTkdWSUxMRSBSRCBCSVJNSU5HSEFNIDM1MjE1ZGQCAw8PFgIfAgUJNy8yMC8yMDE4ZGQCBA8PFgIfAgUBWWRkAgYPZBYKZg8PFgIfAgUFMTgwMjNkZAIBD2QWAmYPDxYEHwIFAjg1HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE4MDIzJkluc3BOYnI9NDNkZAICD2QWBAIBDw8WAh8CBQdBIFdJTkdTZGQCAw8PFgIfAgUiMTY4MCBNT05UQ0xBSVIgUkQgQklSTUlOR0hBTSAzNTIxMGRkAgMPDxYCHwIFCTUvMTcvMjAxOGRkAgQPDxYCHwIFAVlkZAIHD2QWCmYPDxYCHwIFBTIyNzk4ZGQCAQ9kFgJmDw8WBB8CBQI5MR8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMjc5OCZJbnNwTmJyPTNkZAICD2QWBAIBDw8WAh8CBQ1BLTEgRk9PRCBNQVJUZGQCAw8PFgIfAgUfMjIxNiAyNFRIIFNUIE4gQklSTUlOR0hBTSAzNTIzNGRkAgMPDxYCHwIFCTcvMTcvMjAxOGRkAgQPDxYCHwIFAU5kZAIID2QWCmYPDxYCHwIFBTE4NjgwZGQCAQ9kFgJmDw8WBB8CBQI5Mx8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xODY4MCZJbnNwTmJyPTMxZGQCAg9kFgQCAQ8PFgIfAgUYQS4gSC4gUEFSS0VSIEhJR0ggU0NIT09MZGQCAw8PFgIfAgUdOTAwIDRUSCBTVCBOIEJJUk1JTkdIQU0gMzUyMDRkZAIDDw8WAh8CBQg1LzkvMjAxOGRkAgQPDxYCHwIFAVlkZAIJD2QWCmYPDxYCHwIFBTIwMTE3ZGQCAQ9kFgJmDw8WBB8CBQI4OR8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMDExNyZJbnNwTmJyPTdkZAICD2QWBAIBDw8WAh8CBR5BLkguIFBBUktFUiBIUyBIT01FIENPTkNFU1NJT05kZAIDDw8WAh8CBSs0MDAgQUJSQUhBTSBXT09EUyBKUi4gQkxWRCBCSVJNSU5HSEFNIDM1MjA0ZGQCAw8PFgIfAgUJMTEvMy8yMDE3ZGQCBA8PFgIfAgUBWWRkAgoPZBYKZg8PFgIfAgUFMjAxMThkZAIBD2QWAmYPDxYEHwIFAjk0HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIwMTE4Jkluc3BOYnI9N2RkAgIPZBYEAgEPDxYCHwIFIUEuSC4gUEFSS0VSIEhTIFZJU0lUT1IgQ09OQ0VTU0lPTmRkAgMPDxYCHwIFKzQwMCBBQlJBSEFNIFdPT0RTIEpSLiBCTFZEIEJJUk1JTkdIQU0gMzUyMDRkZAIDDw8WAh8CBQkxMS8zLzIwMTdkZAIEDw8WAh8CBQFZZGQCCw9kFgpmDw8WAh8CBQUxMzk1MWRkAgEPZBYCZg8PFgQfAgUCOTQfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTM5NTEmSW5zcE5icj0xMWRkAgIPZBYEAgEPDxYCHwIFCEFBIFNIRUxMZGQCAw8PFgIfAgUgMTUwMCAzMVNUIFNUIFNXIEJJUk1JTkdIQU0gMzUyMjFkZAIDDw8WAh8CBQk3LzE5LzIwMThkZAIEDw8WAh8CBQFZZGQCDA9kFgpmDw8WAh8CBQQ4MzU0ZGQCAQ9kFgJmDw8WBB8CBQI5OR8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj04MzU0Jkluc3BOYnI9MzRkZAICD2QWBAIBDw8WAh8CBRxBQkMgQ0hJTEQgREVWRUxPUE1FTlQgQ0VOVEVSZGQCAw8PFgIfAgUkNzcxIFNIQURFUyBNT1VOVEFJTiBQTFogSE9PVkVSIDM1MjI2ZGQCAw8PFgIfAgUJNi8yMC8yMDE4ZGQCBA8PFgIfAgUBWWRkAg0PZBYKZg8PFgIfAgUEODcxOGRkAgEPZBYCZg8PFgQfAgUCOTYfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9ODcxOCZJbnNwTmJyPTQzZGQCAg9kFgQCAQ8PFgIfAgUcQUJDIENISUxEIERFVkVMT1BNRU5UIENFTlRFUmRkAgMPDxYCHwIFITEzMDAgQ09MVU1CSUFOQSBSRCBIT01FV09PRCAzNTIwOWRkAgMPDxYCHwIFCTQvMTgvMjAxOGRkAgQPDxYCHwIFAVlkZAIOD2QWCmYPDxYCHwIFAzQ1MmRkAgEPZBYCZg8PFgQfAgUCOTYfAwUvfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9NDUyJkluc3BOYnI9MzFkZAICD2QWBAIBDw8WAh8CBQxBQkMgREFZIENBUkVkZAIDDw8WAh8CBSU1MDEgUFJJTkNFVE9OIEFWRSBTVyBCSVJNSU5HSEFNIDM1MjExZGQCAw8PFgIfAgUJMy8yOS8yMDE4ZGQCBA8PFgIfAgUBWWRkAg8PZBYKZg8PFgIfAgUEMzAxNGRkAgEPZBYCZg8PFgQfAgUCOTMfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MzAxNCZJbnNwTmJyPTQzZGQCAg9kFgQCAQ8PFgIfAgUgQUJDIERBWUNBUkUgJiBLSU5ERVJHQVJURU4sIElOQy5kZAIDDw8WAh8CBSA2MTAgQ09MVU1CSUFOQSBSRCBIT01FV09PRCAzNTIwOWRkAgMPDxYCHwIFCDUvMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAhAPZBYKZg8PFgIfAgUFMjI0MzRkZAIBD2QWAmYPDxYEHwIFAjk3HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyNDM0Jkluc3BOYnI9N2RkAgIPZBYEAgEPDxYCHwIFBUFCSElTZGQCAw8PFgIfAgUgMzAwIFNVTU1JVCBCTFZEIEJJUk1JTkdIQU0gMzUyNDNkZAIDDw8WAh8CBQk3LzEwLzIwMThkZAIEDw8WAh8CBQFZZGQCEQ9kFgpmDw8WAh8CBQUxNTYwMWRkAgEPZBYCZg8PFgQfAgUCOTQfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTU2MDEmSW5zcE5icj03MmRkAgIPZBYEAgEPDxYCHwIFGEFCUkFNUyBFTEVNRU5UQVJZIFNDSE9PTGRkAgMPDxYCHwIFHTExMDAgMjNSRCBTVCBOIEJFU1NFTUVSIDM1MDIwZGQCAw8PFgIfAgUINS8xLzIwMThkZAIEDw8WAh8CBQFZZGQCEg9kFgpmDw8WAh8CBQUyMjc5NmRkAgEPZBYCZg8PFgQfAgUCOTkfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjI3OTYmSW5zcE5icj00ZGQCAg9kFgQCAQ8PFgIfAgUPQUNBREVNWSBDSEVWUk9OZGQCAw8PFgIfAgUdNTAzNiBGT1JEIFBLV1kgQkVTU0VNRVIgMzUwMjJkZAIDDw8WAh8CBQg4LzIvMjAxOGRkAgQPDxYCHwIFAVlkZAITD2QWCmYPDxYCHwIFBTE3MTYxZGQCAQ9kFgJmDw8WBB8CBQI5Nx8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNzE2MSZJbnNwTmJyPTI2ZGQCAg9kFgQCAQ8PFgIfAgUNQUNBREVNWSBTSEVMTGRkAgMPDxYCHwIFHTczNiBBQ0FERU1ZIERSIEJFU1NFTUVSIDM1MDIyZGQCAw8PFgIfAgUJNC8xMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAhQPZBYKZg8PFgIfAgUFMTcyOTdkZAIBD2QWAmYPDxYEHwIFAjk0HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE3Mjk3Jkluc3BOYnI9MzRkZAICD2QWBAIBDw8WAh8CBRRBQ0FQVUxDTyBCQVIgJiBHUklMTGRkAgMPDxYCHwIFJDQzMCBHUkVFTiBTUFJJTkdTIEhXWSBIT01FV09PRCAzNTIwOWRkAgMPDxYCHwIFCDYvNC8yMDE4ZGQCBA8PFgIfAgUBWWRkAhUPZBYKZg8PFgIfAgUFMjIwMTZkZAIBD2QWAmYPDxYEHwIFAjk0HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyMDE2Jkluc3BOYnI9N2RkAgIPZBYEAgEPDxYCHwIFDEFDQ1VSQVRFIElDRWRkAgMPDxYCHwIFHjE3MDEgQVZFTlVFIEYgQklSTUlOR0hBTSAzNTIxNGRkAgMPDxYCHwIFCTYvMjgvMjAxOGRkAgQPDxYCHwIFAVlkZAIWD2QWCmYPDxYCHwIFBTIyNDM1ZGQCAQ9kFgJmDw8WBB8CBQI5MB8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMjQzNSZJbnNwTmJyPTNkZAICD2QWBAIBDw8WAh8CBSVBQ0lQQ08gRU1QTE9ZRUUgQ0FGRSAtIENBTlRFRU4gRElOSU5HZGQCAw8PFgIfAgUhMTUwMSAzMVNUICBBVkUgTiBCSVJNSU5HSEFNIDM1MjA3ZGQCAw8PFgIfAgUJMTEvMS8yMDE3ZGQCBA8PFgIfAgUBWWRkAhcPZBYKZg8PFgIfAgUFMjE1NDJkZAIBD2QWAmYPDxYEHwIFAjkzHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxNTQyJkluc3BOYnI9MTRkZAICD2QWBAIBDw8WAh8CBRpBQ1RPTiBST0FEIERBWUxJR0hUIERPTlVUU2RkAgMPDxYCHwIFHTI0MDkgQUNUT04gIFJEIFZFU1RBVklBIDM1MjQzZGQCAw8PFgIfAgUINS85LzIwMThkZAIEDw8WAh8CBQFZZGQCGA9kFgpmDw8WAh8CBQUxNTA1MGRkAgEPZBYCZg8PFgQfAgUCOTcfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTUwNTAmSW5zcE5icj0zMWRkAgIPZBYEAgEPDxYCHwIFEEFDVE9OIFJPQUQgU0hFTExkZAIDDw8WAh8CBR4yODkwIEFDVE9OIFJEIEJJUk1JTkdIQU0gMzUyNDNkZAIDDw8WAh8CBQgxLzUvMjAxOGRkAgQPDxYCHwIFAVlkZAIZD2QWCmYPDxYCHwIFBTE1NTQzZGQCAQ9kFgJmDw8WBB8CBQMxMDAfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTU1NDMmSW5zcE5icj00NGRkAgIPZBYEAgEPDxYCHwIFHEFEQU1TVklMTEUgRUxFTUVOVEFSWSBTQ0hPT0xkZAIDDw8WAh8CBR80NjAwIE1JRFdBWSBSRCBBREFNU1ZJTExFIDM1MDA1ZGQCAw8PFgIfAgUJNS8xNi8yMDE4ZGQCBA8PFgIfAgUBWWRkAhoPZBYKZg8PFgIfAgUFMTg1NzZkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE4NTc2Jkluc3BOYnI9MjZkZAICD2QWBAIBDw8WAh8CBRJBREFNU1ZJTExFIEpFVCBQRVBkZAIDDw8WAh8CBR0zNjE2IE1BSU4gU1QgQURBTVNWSUxMRSAzNTAwNWRkAgMPDxYCHwIFCTYvMTMvMjAxOGRkAgQPDxYCHwIFAVlkZAIbD2QWCmYPDxYCHwIFBTE0MTkwZGQCAQ9kFgJmDw8WBB8CBQMxMDAfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTQxOTAmSW5zcE5icj0zMWRkAgIPZBYEAgEPDxYCHwIFE0FEQU1TVklMTEUgTUFSQVRIT05kZAIDDw8WAh8CBSw1NDAxIFZFVEVSQU5TIE1FTU9SSUFMIFBLV1kgQURBTVNWSUxMRSAzNTAwNWRkAgMPDxYCHwIFCTUvMTEvMjAxOGRkAgQPDxYCHwIFAVlkZAIcD2QWCmYPDxYCHwIFBTE5MDc1ZGQCAQ9kFgJmDw8WBB8CBQI5Nh8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xOTA3NSZJbnNwTmJyPTE3ZGQCAg9kFgQCAQ8PFgIfAgUTQURBTVNWSUxMRSBPTkUgU1RPUGRkAgMPDxYCHwIFHzM2NDUgR1JBWSAgQVZFIEFEQU1TVklMTEUgMzUwMDVkZAIDDw8WAh8CBQkzLzI2LzIwMThkZAIEDw8WAh8CBQFZZGQCHQ9kFgpmDw8WAh8CBQUxODc2NGRkAgEPZBYCZg8PFgQfAgUCODQfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTg3NjQmSW5zcE5icj04ZGQCAg9kFgQCAQ8PFgIfAgUpQURBTVNWSUxMRSBQQVJLIEZPT1RCQUxMIENPTkNFU1NJT04gU1RBTkRkZAIDDw8WAh8CBR85MDEgRE9HV09PRCBSRCBBREFNU1ZJTExFIDM1MDA1ZGQCAw8PFgIfAgUJNC8yMS8yMDE3ZGQCBA8PFgIfAgUBWWRkAh4PZBYKZg8PFgIfAgUFMTgyNjRkZAIBD2QWAmYPDxYEHwIFAjkxHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE4MjY0Jkluc3BOYnI9MTdkZAICD2QWBAIBDw8WAh8CBQ1BREVOIEZPT0RNQVJUZGQCAw8PFgIfAgUdMjgwMSA5VEggQVZFIE4gQkVTU0VNRVIgMzUwMjBkZAIDDw8WAh8CBQgzLzUvMjAxOGRkAgQPDxYCHwIFAVlkZAIfD2QWCmYPDxYCHwIFBTIxMTUxZGQCAQ9kFgJmDw8WBB8CBQI5NB8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMTE1MSZJbnNwTmJyPTE3ZGQCAg9kFgQCAQ8PFgIfAgULQURFTiBNQVJLRVRkZAIDDw8WAh8CBSUxMTM1IFBJTlNPTiBWQUxMRVkgUEtXWSBUQVJSQU5UIDM1MjE3ZGQCAw8PFgIfAgUJMy8yMS8yMDE4ZGQCBA8PFgIfAgUBWWRkAiAPZBYKZg8PFgIfAgUFMjMwODNkZAIBD2QWAmYPDxYEHwIFAjkwHwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIzMDgzJkluc3BOYnI9MWRkAgIPZBYEAgEPDxYCHwIFDUFER0VSIEdST0NFUllkZAIDDw8WAh8CBRk3MzAxIEpPSE5TIFJEIEFER0VSIDM1MDA2ZGQCAw8PFgIfAgUIMi82LzIwMThkZAIEDw8WAh8CBQFZZGQCIQ9kFgpmDw8WAh8CBQUyMjk2NGRkAgEPZBYCZg8PFgQfAgUCOTkfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjI5NjQmSW5zcE5icj0zZGQCAg9kFgQCAQ8PFgIfAgUeQURPUkVEIFNXRUVUUyBAIENoZWZzIFdvcmtzaG9wZGQCAw8PFgIfAgUaMzQzOSBMT1JOQSBMTiBIT09WRVIgMzUyMTZkZAIDDw8WAh8CBQk2LzEyLzIwMThkZAIEDw8WAh8CBQFZZGQCIg9kFgpmDw8WAh8CBQUxNTczNGRkAgEPZBYCZg8PFgQfAgUCOTUfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTU3MzQmSW5zcE5icj00N2RkAgIPZBYEAgEPDxYCHwIFF0FEVkVOVCBFUElTQ09QQUwgU0NIT09MZGQCAw8PFgIfAgUfMjAxOSA2VEggQVZFIE4gQklSTUlOR0hBTSAzNTIwM2RkAgMPDxYCHwIFCDUvNC8yMDE4ZGQCBA8PFgIfAgUBWWRkAiMPZBYKZg8PFgIfAgUFMTY0NzBkZAIBD2QWAmYPDxYEHwIFAzEwMB8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNjQ3MCZJbnNwTmJyPTM1ZGQCAg9kFgQCAQ8PFgIfAgUYQUZDIFNVU0hJIEAgUFVCTElYICMxMDU5ZGQCAw8PFgIfAgUiMTMyNSBNT05UQ0xBSVIgUkQgQklSTUlOR0hBTSAzNTIxMGRkAgMPDxYCHwIFCDMvMS8yMDE4ZGQCBA8PFgIfAgUBWWRkAiQPZBYKZg8PFgIfAgUFMjI5ODNkZAIBD2QWAmYPDxYEHwIFAjk5HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyOTgzJkluc3BOYnI9NmRkAgIPZBYEAgEPDxYCHwIFGEFGQyBTVVNISSBAIFBVQkxJWCAjMTA4MmRkAgMPDxYCHwIFITcyNzIgR0FEU0RFTiBIV1kgVFJVU1NWSUxMRSAzNTE3M2RkAgMPDxYCHwIFCDcvOS8yMDE4ZGQCBA8PFgIfAgUBWWRkAiUPZBYKZg8PFgIfAgUFMjE5NTBkZAIBD2QWAmYPDxYEHwIFAjk5HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxOTUwJkluc3BOYnI9MTlkZAICD2QWBAIBDw8WAh8CBRhBRkMgU1VTSEkgQCBQVUJMSVggIzEwODVkZAIDDw8WAh8CBSQzMTQxIE9WRVJUT04gUkQgTU9VTlRBSU4gQlJPT0sgMzUyMjNkZAIDDw8WAh8CBQk3LzExLzIwMThkZAIEDw8WAh8CBQFZZGQCJg9kFgpmDw8WAh8CBQUyMTMxM2RkAgEPZBYCZg8PFgQfAgUCOTQfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjEzMTMmSW5zcE5icj0xNWRkAgIPZBYEAgEPDxYCHwIFGEFGQyBTVVNISSBAIFBVQkxJWCAjMTIwNmRkAgMPDxYCHwIFIjY1NSBGSUVMRFNUT1dOIFJEIEdBUkRFTkRBTEUgMzUwNzFkZAIDDw8WAh8CBQkxLzIyLzIwMThkZAIEDw8WAh8CBQFZZGQCJw9kFgpmDw8WAh8CBQUxODIyOGRkAgEPZBYCZg8PFgQfAgUCOTIfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTgyMjgmSW5zcE5icj0zOGRkAgIPZBYEAgEPDxYCHwIFGEFGQyBTVVNISSBAIFBVQkxJWCAjMTIwN2RkAgMPDxYCHwIFIDE1ODQgTU9OVEdPTUVSWSBIV1kgSE9PVkVSIDM1MjE2ZGQCAw8PFgIfAgUJNy8xMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAigPZBYKZg8PFgIfAgUFMjI0MDJkZAIBD2QWAmYPDxYEHwIFAjk5HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyNDAyJkluc3BOYnI9NmRkAgIPZBYEAgEPDxYCHwIFGEFGQyBTVVNISSBAIFBVQkxJWCAjMTUxMmRkAgMPDxYCHwIFHjIzMCAyMFRIIFNUIFMgQklSTUlOR0hBTSAzNTIzM2RkAgMPDxYCHwIFCTUvMzAvMjAxOGRkAgQPDxYCHwIFAVlkZAIpD2QWCmYPDxYCHwIFBTIyNDA0ZGQCAQ9kFgJmDw8WBB8CBQI5OR8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMjQwNCZJbnNwTmJyPTEwZGQCAg9kFgQCAQ8PFgIfAgUYQUZDIFNVU0hJIEAgUFVCTElYICMxNTQ1ZGQCAw8PFgIfAgUgMzA0MCBIRUFMVEhZICBXQVkgVkVTVEFWSUEgMzUyNDNkZAIDDw8WAh8CBQk2LzI1LzIwMThkZAIEDw8WAh8CBQFZZGQCKg9kFgpmDw8WAh8CBQUxNjI1OWRkAgEPZBYCZg8PFgQfAgUCOTgfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTYyNTkmSW5zcE5icj00M2RkAgIPZBYEAgEPDxYCHwIFF0FGQyBTVVNISSBAIFBVQkxJWCAjMTY1ZGQCAw8PFgIfAgUkNDExIEdSRUVOIFNQUklOR1MgSFdZIEhPTUVXT09EIDM1MjA5ZGQCAw8PFgIfAgUJNS8yOS8yMDE4ZGQCBA8PFgIfAgUBWWRkAisPZBYKZg8PFgIfAgUFMTY5NzNkZAIBD2QWAmYPDxYEHwIFAjk5HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE2OTczJkluc3BOYnI9NDRkZAICD2QWBAIBDw8WAh8CBRdBRkMgU1VTSEkgQCBQVUJMSVggIzgzOWRkAgMPDxYCHwIFIzI1NDMgSk9ITiBIQVdLSU5TIFBLV1kgSE9PVkVSIDM1MjQ0ZGQCAw8PFgIfAgUINi82LzIwMThkZAIEDw8WAh8CBQFZZGQCLA9kFgpmDw8WAh8CBQUxNDkyMGRkAgEPZBYCZg8PFgQfAgUCOTkfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTQ5MjAmSW5zcE5icj02OWRkAgIPZBYEAgEPDxYCHwIFF0FGQyBTVVNISSBAIFBVQkxJWCAjODQyZGQCAw8PFgIfAgUhNzg0IE1PTlRHT01FUlkgSFdZIFZFU1RBVklBIDM1MjE2ZGQCAw8PFgIfAgUJMS8yOS8yMDE4ZGQCBA8PFgIfAgUBWWRkAi0PZBYKZg8PFgIfAgUFMjEzMTRkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxMzE0Jkluc3BOYnI9MjRkZAICD2QWBAIBDw8WAh8CBTJBRkMgU1VTSEkgQCBVQUIgSG9zcGl0YWwgTm9ydGggUGF2aWxpb24gRm9vZCBDb3VydGRkAgMPDxYCHwIFHzE4MDIgNlRIIEFWRSBTIEJJUk1JTkdIQU0gMzUyMzNkZAIDDw8WAh8CBQk1LzI5LzIwMThkZAIEDw8WAh8CBQFZZGQCLg9kFgpmDw8WAh8CBQUyMTEyM2RkAgEPZBYCZg8PFgQfAgUCOTkfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjExMjMmSW5zcE5icj0xMWRkAgIPZBYEAgEPDxYCHwIFDEFJUkZBUkUgSU5DLmRkAgMPDxYCHwIFIjI2MTIgTEFORSBQQVJLIFJEIEJJUk1JTkdIQU0gMzUyMjNkZAIDDw8WAh8CBQgyLzEvMjAxOGRkAgQPDxYCHwIFAVlkZAIvD2QWCmYPDxYCHwIFBTE0MjIxZGQCAQ9kFgJmDw8WBB8CBQI5Nx8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNDIyMSZJbnNwTmJyPTE1ZGQCAg9kFgQCAQ8PFgIfAgULQUlSUE9SVCBJTk5kZAIDDw8WAh8CBR83NTAyIDVUSCBBVkUgTiBCSVJNSU5HSEFNIDM1MjA2ZGQCAw8PFgIfAgUJNC8yNC8yMDE4ZGQCBA8PFgIfAgUBWWRkAjAPZBYKZg8PFgIfAgUFMTcyNzhkZAIBD2QWAmYPDxYEHwIFAjk1HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE3Mjc4Jkluc3BOYnI9MzNkZAICD2QWBAIBDw8WAh8CBQ5BSVJQT1JUIExPVU5HRWRkAgMPDxYCHwIFHzE0MDkgNTBUSCBTVCBOIEJJUk1JTkdIQU0gMzUyMTJkZAIDDw8WAh8CBQgzLzcvMjAxOGRkAgQPDxYCHwIFAVlkZAIxD2QWCmYPDxYCHwIFBTIxMjQ0ZGQCAQ9kFgJmDw8WBB8CBQI5Mx8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMTI0NCZJbnNwTmJyPTEzZGQCAg9kFgQCAQ8PFgIfAgUXQUlSUE9SVCBNSU5JIE1BUlQtU0hFTExkZAIDDw8WAh8CBSg0MDEwIE1FU1NFUiBBSVJQT1JUIEhXWSBCSVJNSU5HSEFNIDM1MjIyZGQCAw8PFgIfAgUJNi8yNi8yMDE4ZGQCBA8PFgIfAgUBWWRkAjIPZBYKZg8PFgIfAgUFMTgxMjFkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE4MTIxJkluc3BOYnI9MTdkZAICD2QWBAIBDw8WAh8CBRFBSVJQT1JUIFNIRUxMICMgMmRkAgMPDxYCHwIFMDUwMTcgUklDSEFSRCBBUlJJTkdUT04gSlIuIEJMVkQgQklSTUlOR0hBTSAzNTIxMmRkAgMPDxYCHwIFCTIvMjMvMjAxOGRkAgQPDxYCHwIFAVlkZAIzD2QWCmYPDxYCHwIFBTE3OTY1ZGQCAQ9kFgJmDw8WBB8CBQI5OR8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNzk2NSZJbnNwTmJyPTIwZGQCAg9kFgQCAQ8PFgIfAgUQQUlSUE9SVCBTSEVMTCAjMWRkAgMPDxYCHwIFIDUxMTcgMTBUSCBBVkUgTiBCSVJNSU5HSEFNIDM1MjEyZGQCAw8PFgIfAgUIMy81LzIwMThkZAIEDw8WAh8CBQFZZGQCNA9kFgpmDw8WAh8CBQUyMDc1MmRkAgEPZBYCZg8PFgQfAgUCOTMfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjA3NTImSW5zcE5icj0zMGRkAgIPZBYEAgEPDxYCHwIFDUFJUlBPUlQgU1RPUkVkZAIDDw8WAh8CBSgzODI4IE1FU1NFUiBBSVJQT1JUIEhXWSBCSVJNSU5HSEFNIDM1MjIyZGQCAw8PFgIfAgUINS80LzIwMThkZAIEDw8WAh8CBQFZZGQCNQ9kFgpmDw8WAh8CBQUyMzIwMGRkAgEPZBYCZg8PFgQfAgUCOTEfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjMyMDAmSW5zcE5icj0yZGQCAg9kFgQCAQ8PFgIfAgUSQUlSUE9SVCBTVE9SRSBDQUZFZGQCAw8PFgIfAgUeNzIwIDM5VEggU1QgTiBCSVJNSU5HSEFNIDM1MjIyZGQCAw8PFgIfAgUJNy8xMC8yMDE4ZGQCBA8PFgIfAgUBWWRkAjYPZBYKZg8PFgIfAgUFMjEzODdkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxMzg3Jkluc3BOYnI9NGRkAgIPZBYEAgEPDxYCHwIFEkFKUyBESVNDT1VOVCBTVE9SRWRkAgMPDxYCHwIFHzM0MDAgMjZUSCBTVCBOIEJJUk1JTkdIQU0gMzUyMDdkZAIDDw8WAh8CBQkzLzI4LzIwMTdkZAIEDw8WAh8CBQFZZGQCNw9kFgpmDw8WAh8CBQUxODA2MGRkAgEPZBYCZg8PFgQfAgUCOTkfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTgwNjAmSW5zcE5icj0yN2RkAgIPZBYEAgEPDxYCHwIFGUFLU0hBUlJBSiAgTExDIChNYXJhdGhvbilkZAIDDw8WAh8CBR0yNDI5IDE5VEggU1QgTiBCRVNTRU1FUiAzNTAyMGRkAgMPDxYCHwIFCDMvNy8yMDE4ZGQCBA8PFgIfAgUBWWRkAjgPZBYKZg8PFgIfAgUFMTcxMTBkZAIBD2QWAmYPDxYEHwIFAzEwMB8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNzExMCZJbnNwTmJyPTEzZGQCAg9kFgQCAQ8PFgIfAgUjQUxBQkFNQSBKQVpaIEhBTEwgT0YgRkFNRSAgKENBUlZFUilkZAIDDw8WAh8CBR8xNjMxIDRUSCBBVkUgTiBCSVJNSU5HSEFNIDM1MjAzZGQCAw8PFgIfAgUJNS8xOS8yMDE3ZGQCBA8PFgIfAgUBWWRkAjkPZBYKZg8PFgIfAgUFMTU3MzJkZAIBD2QWAmYPDxYEHwIFAjkxHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE1NzMyJkluc3BOYnI9NDVkZAICD2QWBAIBDw8WAh8CBRtBTEFCQU1BIFNDSE9PTCBPRiBGSU5FIEFSVFNkZAIDDw8WAh8CBR8xODAwIDhUSCBBVkUgTiBCSVJNSU5HSEFNIDM1MjAzZGQCAw8PFgIfAgUJNS8xNi8yMDE4ZGQCBA8PFgIfAgUBWWRkAjoPZBYKZg8PFgIfAgUFMjIzNTBkZAIBD2QWAmYPDxYEHwIFAjg3HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyMzUwJkluc3BOYnI9OWRkAgIPZBYEAgEPDxYCHwIFH0FMQUJBTUEgU1BPUlRTIEFORCBFVkVOVCBDRU5URVJkZAIDDw8WAh8CBRkxMDAwIFJWIFRSQ0UgSE9PVkVSIDM1MjQ0ZGQCAw8PFgIfAgUJNS8yMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAjsPZBYKZg8PFgIfAgUFMTc4NTVkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE3ODU1Jkluc3BOYnI9MzFkZAICD2QWBAIBDw8WAh8CBRxBTEFCQU1BIFRIRUFUUkUgQkFOUVVFVCBST09NZGQCAw8PFgIfAgUfMTgxNyAzUkQgQVZFIE4gQklSTUlOR0hBTSAzNTIwM2RkAgMPDxYCHwIFCDQvMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAjwPZBYKZg8PFgIfAgUFMTM1NDFkZAIBD2QWAmYPDxYEHwIFAzEwMB8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xMzU0MSZJbnNwTmJyPTI4ZGQCAg9kFgQCAQ8PFgIfAgUbQUxBQkFNQSBUSEVBVFJFIENPTkNFU1NJT05TZGQCAw8PFgIfAgUfMTgxNyAzUkQgQVZFIE4gQklSTUlOR0hBTSAzNTIwM2RkAgMPDxYCHwIFCDQvMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAj0PZBYKZg8PFgIfAgUFMTY3OTRkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE2Nzk0Jkluc3BOYnI9MTJkZAICD2QWBAIBDw8WAh8CBQRBTERJZGQCAw8PFgIfAgUdNzEwIEFDQURFTVkgRFIgQkVTU0VNRVIgMzUwMjJkZAIDDw8WAh8CBQk0LzEwLzIwMThkZAIEDw8WAh8CBQFZZGQCPg9kFgpmDw8WAh8CBQUxNzAyMmRkAgEPZBYCZg8PFgQfAgUCOTcfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTcwMjImSW5zcE5icj0xN2RkAgIPZBYEAgEPDxYCHwIFBEFMRElkZAIDDw8WAh8CBSM1OTYwIENIQUxLVklMTEUgUkQgVFJVU1NWSUxMRSAzNTIzNWRkAgMPDxYCHwIFCTYvMTAvMjAxNmRkAgQPDxYCHwIFAVlkZAI/D2QWCmYPDxYCHwIFBTIwMzg2ZGQCAQ9kFgJmDw8WBB8CBQMxMDAfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjAzODYmSW5zcE5icj03ZGQCAg9kFgQCAQ8PFgIfAgUEQUxESWRkAgMPDxYCHwIFITE2MDEgTU9SUklTICBBVkUgRlVMVE9OREFMRSAzNTA2OGRkAgMPDxYCHwIFCDgvMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAkAPZBYKZg8PFgIfAgUFMjExNDFkZAIBD2QWAmYPDxYEHwIFAjk3HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxMTQxJkluc3BOYnI9NGRkAgIPZBYEAgEPDxYCHwIFCUFMREkgIyAyOWRkAgMPDxYCHwIFLzI4OTEgQUxMSVNPTiBCT05ORVRUIE1FTU9SSUFMIERSIEhVRVlUT1dOIDM1MDIzZGQCAw8PFgIfAgUJMi8xNi8yMDE2ZGQCBA8PFgIfAgUBWWRkAkEPZBYKZg8PFgIfAgUFMTgxNzhkZAIBD2QWAmYPDxYEHwIFAjkxHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE4MTc4Jkluc3BOYnI9MTRkZAICD2QWBAIBDw8WAh8CBRBBTERJIEZPT0QgTUFSS0VUZGQCAw8PFgIfAgUlNzQwMCBDUkVTVFdPT0QgQkxWRC4gQklSTUlOR0hBTSAzNTIxMGRkAgMPDxYCHwIFCTExLzcvMjAxN2RkAgQPDxYCHwIFAVlkZAJCD2QWCmYPDxYCHwIFBTE3MDgwZGQCAQ9kFgJmDw8WBB8CBQI5NB8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNzA4MCZJbnNwTmJyPTEwZGQCAg9kFgQCAQ8PFgIfAgUPQUxESSBGT09EIFNUT1JFZGQCAw8PFgIfAgUkNDI4IEdSRUVOIFNQUklOR1MgSFdZIEhPTUVXT09EIDM1MjA5ZGQCAw8PFgIfAgUJNi8xOS8yMDE3ZGQCBA8PFgIfAgUBWWRkAkMPZBYKZg8PFgIfAgUFMTc1MzhkZAIBD2QWAmYPDxYEHwIFAjk0HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE3NTM4Jkluc3BOYnI9MTBkZAICD2QWBAIBDw8WAh8CBRNBTERJIEZPT0QgU1RPUkUgIzM0ZGQCAw8PFgIfAgUhNTIwIEdFTkUgUkVFRCBSRCBCSVJNSU5HSEFNIDM1MjE1ZGQCAw8PFgIfAgUIMy83LzIwMThkZAIEDw8WAh8CBQFZZGQCRA9kFgpmDw8WAh8CBQQ5NzU0ZGQCAQ9kFgJmDw8WBB8CBQI5MR8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj05NzU0Jkluc3BOYnI9NTBkZAICD2QWBAIBDw8WAh8CBQ1BTEVUSElBIEhPVVNFZGQCAw8PFgIfAgUfNDI0NiA1VEggQVZFIFMgQklSTUlOR0hBTSAzNTIyMmRkAgMPDxYCHwIFCTMvMjAvMjAxN2RkAgQPDxYCHwIFAVlkZAJFD2QWCmYPDxYCHwIFBTIxNjc4ZGQCAQ9kFgJmDw8WBB8CBQI4OR8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMTY3OCZJbnNwTmJyPTE3ZGQCAg9kFgQCAQ8PFgIfAgUKQUxFWEFOREVSU2RkAgMPDxYCHwIFJDM4MDAgQ09MT05OQURFIFBLV1kgQklSTUlOR0hBTSAzNTI0M2RkAgMPDxYCHwIFCDMvNy8yMDE4ZGQCBA8PFgIfAgUBWWRkAkYPZBYKZg8PFgIfAgUFMjAwNzNkZAIBD2QWAmYPDxYEHwIFAjgyHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIwMDczJkluc3BOYnI9MTJkZAICD2QWBAIBDw8WAh8CBRNBTEZPUkQgQVZFTlVFIFNIRUxMZGQCAw8PFgIfAgUcMTE3MCBBTEZPUkQgQVZFIEhPT1ZFUiAzNTIyNmRkAgMPDxYCHwIFCDcvMi8yMDE4ZGQCBA8PFgIfAgUBWWRkAkcPZBYKZg8PFgIfAgUFMjI5ODFkZAIBD2QWAmYPDxYEHwIFAjk3HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyOTgxJkluc3BOYnI9NGRkAgIPZBYEAgEPDxYCHwIFE0FMRlJFRE9TIFBJWlpBIENBRkVkZAIDDw8WAh8CBSQ4MDMgR1JFRU4gU1BSSU5HUyBIV1kgSE9NRVdPT0QgMzUyMDlkZAIDDw8WAh8CBQk3LzI2LzIwMThkZAIEDw8WAh8CBQFZZGQCSA9kFgpmDw8WAh8CBQUyMjgxN2RkAgEPZBYCZg8PFgQfAgUCOTgfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjI4MTcmSW5zcE5icj00ZGQCAg9kFgQCAQ8PFgIfAgURQUxMIEFNRVJJQ0FOIERFTElkZAIDDw8WAh8CBRwzMDE2IENPUk5FUiBSRCBXQVJSSU9SIDM1MTgwZGQCAw8PFgIfAgUJMi8yNy8yMDE4ZGQCBA8PFgIfAgUBWWRkAkkPZBYKZg8PFgIfAgUFMTE3MzNkZAIBD2QWAmYPDxYEHwIFAjk4HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTExNzMzJkluc3BOYnI9NDJkZAICD2QWBAIBDw8WAh8CBR1BTEwgSVMgV0VMTCBDSFJJU1RJQU4gQUNBREVNWWRkAgMPDxYCHwIFLzMwOTAgQUxMSVNPTiBCT05ORVRUIE1FTU9SSUFMIERSIEhVRVlUT1dOIDM1MDIzZGQCAw8PFgIfAgUJMTIvNC8yMDE3ZGQCBA8PFgIfAgUBWWRkAkoPZBYKZg8PFgIfAgUFMjIwMDlkZAIBD2QWAmYPDxYEHwIFAjkyHwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyMDA5Jkluc3BOYnI9NmRkAgIPZBYEAgEPDxYCHwIFFUFMTCBPUklHSU5BTCBQSVpaRVJJQWRkAgMPDxYCHwIFJDQ3NjAgRUFTVEVSTiBWQUxMRVkgUkQgTUNDQUxMQSAzNTExMWRkAgMPDxYCHwIFCTYvMjAvMjAxOGRkAgQPDxYCHwIFAVlkZAJLD2QWCmYPDxYCHwIFBTE2NjExZGQCAQ9kFgJmDw8WBB8CBQI5NB8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xNjYxMSZJbnNwTmJyPTMyZGQCAg9kFgQCAQ8PFgIfAgUUQUxMRU4gIEZPT0QgTUFSVCAjMTFkZAIDDw8WAh8CBSUyMTk3IEVBU1RFUk4gVkFMTEVZIFJEIEJFU1NFTUVSIDM1MDIyZGQCAw8PFgIfAgUIOC8yLzIwMThkZAIEDw8WAh8CBQFZZGQCTA9kFgpmDw8WAh8CBQUxMDQ4OGRkAgEPZBYCZg8PFgQfAgUCOTcfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTA0ODgmSW5zcE5icj0xMmRkAgIPZBYEAgEPDxYCHwIFFEFMTElTT04gQk9OTkVUVCBQQVJLZGQCAw8PFgIfAgUgNTA2IFBJTkVXT09EICBBVkUgSFVFWVRPV04gMzUwMjNkZAIDDw8WAh8CBQg1LzIvMjAxN2RkAgQPDxYCHwIFAVlkZAJND2QWCmYPDxYCHwIFBTE5MDUyZGQCAQ9kFgJmDw8WBB8CBQI5Nh8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xOTA1MiZJbnNwTmJyPTM0ZGQCAg9kFgQCAQ8PFgIfAgUNQUxMU1RBUiBESU5FUmRkAgMPDxYCHwIFKjU3MDQgQklSTUlOR1BPUlQgUk9BRCBTWUxWQU4gU1BSSU5HUyAzNTExOGRkAgMPDxYCHwIFCTcvMjMvMjAxOGRkAgQPDxYCHwIFAVlkZAJOD2QWCmYPDxYCHwIFBTIxNDM2ZGQCAQ9kFgJmDw8WBB8CBQI5OR8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMTQzNiZJbnNwTmJyPTEyZGQCAg9kFgQCAQ8PFgIfAgUUQUxMU1RBUiBESU5FUiBTQ09PUFNkZAIDDw8WAh8CBSg1NzA0IEJJUk1JTkdQT1JUIFJEIFNZTFZBTiBTUFJJTkdTIDM1MTE4ZGQCAw8PFgIfAgUJNy8yMy8yMDE4ZGQCBA8PFgIfAgUBWWRkAk8PZBYKZg8PFgIfAgUFMjI2NjhkZAIBD2QWAmYPDxYEHwIFAjk1HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyNjY4Jkluc3BOYnI9N2RkAgIPZBYEAgEPDxYCHwIFE0FMTFNUQVRFIFFVSUNLIE1BUlRkZAIDDw8WAh8CBRw3Njk4IEhJR0hXQVkgNzggVyBET1JBIDM1MDYyZGQCAw8PFgIfAgUJNS8xOC8yMDE4ZGQCBA8PFgIfAgUBWWRkAlAPZBYKZg8PFgIfAgUFMjEzMDNkZAIBD2QWAmYPDxYEHwIFAjk1HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxMzAzJkluc3BOYnI9OGRkAgIPZBYEAgEPDxYCHwIFHEFMT0ZUIEJJUk1JTkdIQU0gU09ITyBTUVVBUkVkZAIDDw8WAh8CBR4xOTAzIDI5VEggQVZFIFMgSE9NRVdPT0QgMzUyMDlkZAIDDw8WAh8CBQg3LzMvMjAxOGRkAgQPDxYCHwIFAVlkZAJRD2QWCmYPDxYCHwIFBTEwMDE1ZGQCAQ9kFgJmDw8WBB8CBQI4Mh8DBTF+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xMDAxNSZJbnNwTmJyPTM3ZGQCAg9kFgQCAQ8PFgIfAgUQQUxTIERFTEkgJiBHUklMTGRkAgMPDxYCHwIFIDE2MjkgMTBUSCBBVkUgUyBCSVJNSU5HSEFNIDM1MjA1ZGQCAw8PFgIfAgUJNy8zMS8yMDE4ZGQCBA8PFgIfAgUBWWRkAlIPZBYKZg8PFgIfAgUFMjEwMDlkZAIBD2QWAmYPDxYEHwIFAjkzHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxMDA5Jkluc3BOYnI9MTVkZAICD2QWBAIBDw8WAh8CBQ5BTHMgT04gU0VWRU5USGRkAgMPDxYCHwIFHzI2MjcgN1RIIEFWRSBTIEJJUk1JTkdIQU0gMzUyMzNkZAIDDw8WAh8CBQkzLzE0LzIwMTdkZAIEDw8WAh8CBQFZZGQCUw9kFgpmDw8WAh8CBQUxNTcxOWRkAgEPZBYCZg8PFgQfAgUCOTcfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTU3MTkmSW5zcE5icj01NGRkAgIPZBYEAgEPDxYCHwIFD0FMVEFNT05UIFNDSE9PTGRkAgMPDxYCHwIFITQ4MDEgQUxUQU1PTlQgUkQgQklSTUlOR0hBTSAzNTIyMmRkAgMPDxYCHwIFCDUvNC8yMDE4ZGQCBA8PFgIfAgUBWWRkAlQPZBYKZg8PFgIfAgUEOTU0MWRkAgEPZBYCZg8PFgQfAgUDMTAwHwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTk1NDEmSW5zcE5icj0yMGRkAgIPZBYEAgEPDxYCHwIFFEFMWVMgU1RFUEhFTlMgQ0VOVEVSZGQCAw8PFgIfAgUgMTIwMCAxMFRIIEFWRSBTIEJJUk1JTkdIQU0gMzUyMDVkZAIDDw8WAh8CBQkzLzI3LzIwMTdkZAIEDw8WAh8CBQFZZGQCVQ9kFgpmDw8WAh8CBQUyMTU1MmRkAgEPZBYCZg8PFgQfAgUCOTAfAwUwfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjE1NTImSW5zcE5icj05ZGQCAg9kFgQCAQ8PFgIfAgUOQU0gUE0gRk9PRE1BUlRkZAIDDw8WAh8CBSIyNDg1IFJPQ0tZIFJJREdFIFJEIFZFU1RBVklBIDM1MjQzZGQCAw8PFgIfAgUJNC8xNi8yMDE4ZGQCBA8PFgIfAgUBWWRkAlYPZBYKZg8PFgIfAgUFMTUxNzdkZAIBD2QWAmYPDxYEHwIFAjkzHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE1MTc3Jkluc3BOYnI9MjhkZAICD2QWBAIBDw8WAh8CBQ1BTS9QTSBFWFBSRVNTZGQCAw8PFgIfAgUfOTkwMSBQQVJLV0FZIEUgQklSTUlOR0hBTSAzNTIxNWRkAgMPDxYCHwIFCTQvMTIvMjAxOGRkAgQPDxYCHwIFAVlkZAJXD2QWCmYPDxYCHwIFBTIyMTI2ZGQCAQ9kFgJmDw8WBB8CBQI5NR8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0yMjEyNiZJbnNwTmJyPTNkZAICD2QWBAIBDw8WAh8CBRBBTUFOQUggRk9PRCBNQVJUZGQCAw8PFgIfAgUhNDkxNyBBSVJQT1JUIEhXWSBCSVJNSU5HSEFNIDM1MjEyZGQCAw8PFgIfAgUJMTAvNC8yMDE2ZGQCBA8PFgIfAgUBWWRkAlgPZBYKZg8PFgIfAgUFMTgwNTNkZAIBD2QWAmYPDxYEHwIFAjkxHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE4MDUzJkluc3BOYnI9MzlkZAICD2QWBAIBDw8WAh8CBRdBTUJST1NJQSAzMTcvR0FCUklFTExBU2RkAgMPDxYCHwIFHjMxNyAxN1RIIFNUIE4gQklSTUlOR0hBTSAzNTIwM2RkAgMPDxYCHwIFCjExLzI3LzIwMTdkZAIEDw8WAh8CBQFZZGQCWQ9kFgpmDw8WAh8CBQUyMDI4MGRkAgEPZBYCZg8PFgQfAgUCOTQfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjAyODAmSW5zcE5icj0xM2RkAgIPZBYEAgEPDxYCHwIFIUFNQyBWRVNUQVZJQSBISUxMUyAgMTAgIC0gUkVNT1RFIGRkAgMPDxYCHwIFIDE5MTEgS0VOVFVDS1kgQVZFIFZFU1RBVklBIDM1MjE2ZGQCAw8PFgIfAgUJNC8yNi8yMDE4ZGQCBA8PFgIfAgUBWWRkAloPZBYKZg8PFgIfAgUFMjAyNzlkZAIBD2QWAmYPDxYEHwIFAjkxHwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIwMjc5Jkluc3BOYnI9MTVkZAICD2QWBAIBDw8WAh8CBR1BTUMgVkVTVEFWSUEgSElMTFMgMTAgLSAgTUFJTmRkAgMPDxYCHwIFITE5MTEgS0VOVFVDS1kgQVZFLiBWRVNUQVZJQSAzNTIxNmRkAgMPDxYCHwIFCjEyLzE0LzIwMTdkZAIEDw8WAh8CBQFZZGQCWw9kFgpmDw8WAh8CBQUyMDAxMGRkAgEPZBYCZg8PFgQfAgUCODkfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MjAwMTAmSW5zcE5icj0yMmRkAgIPZBYEAgEPDxYCHwIFCEFNRVIgTExDZGQCAw8PFgIfAgUaMjAwIDRUSCBBVkUgQkVTU0VNRVIgMzUwMjBkZAIDDw8WAh8CBQk0LzE5LzIwMThkZAIEDw8WAh8CBQFZZGQCXA9kFgpmDw8WAh8CBQUxMzA4N2RkAgEPZBYCZg8PFgQfAgUCOTUfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTMwODcmSW5zcE5icj00MmRkAgIPZBYEAgEPDxYCHwIFEEFNRVJFWCBDQUZFVEVSSUFkZAIDDw8WAh8CBSE3NTk1IEdBRFNERU4gSFdZIFRSVVNTVklMTEUgMzUxNzNkZAIDDw8WAh8CBQk3LzE2LzIwMThkZAIEDw8WAh8CBQFZZGQCXQ9kFgpmDw8WAh8CBQUxOTA1N2RkAgEPZBYCZg8PFgQfAgUCODkfAwUxfi9FSEZTL0ZTU0RldGFpbHMuYXNweD9QZXJtaXROYnI9MTkwNTcmSW5zcE5icj0zN2RkAgIPZBYEAgEPDxYCHwIFDUFNRVJJQ0FOIERFTElkZAIDDw8WAh8CBRwzMDYgT1hNT09SIFJEIEhPTUVXT09EIDM1MjA5ZGQCAw8PFgIfAgUJNS8xNi8yMDE4ZGQCBA8PFgIfAgUBWWRkAl4PZBYKZg8PFgIfAgUFMjE4NzlkZAIBD2QWAmYPDxYEHwIFAjk3HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIxODc5Jkluc3BOYnI9OWRkAgIPZBYEAgEPDxYCHwIFDUFNRVJJQ0FOIERFTElkZAIDDw8WAh8CBRw1NTE5IEdST1ZFIEJMVkQgSE9PVkVSIDM1MjI2ZGQCAw8PFgIfAgUJNi8xOC8yMDE4ZGQCBA8PFgIfAgUBWWRkAl8PZBYKZg8PFgIfAgUFMjI3NDNkZAIBD2QWAmYPDxYEHwIFAjg2HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTIyNzQzJkluc3BOYnI9NGRkAgIPZBYEAgEPDxYCHwIFDUFNRVJJQ0FOIERFTElkZAIDDw8WAh8CBSIxNjgwIE1PTlRDTEFJUiBSRCBCSVJNSU5HSEFNIDM1MjEwZGQCAw8PFgIfAgUJMy8xOS8yMDE4ZGQCBA8PFgIfAgUBWWRkAmAPZBYKZg8PFgIfAgUFMTk2MTVkZAIBD2QWAmYPDxYEHwIFAjk3HwMFMX4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTE5NjE1Jkluc3BOYnI9MjdkZAICD2QWBAIBDw8WAh8CBSFBTUVSSUNBTiBERUxJIC0gQlVGRkFMTyBXSU5HIFdFU1RkZAIDDw8WAh8CBSExOTQwIEJFU1NFTUVSIFJEIEJJUk1JTkdIQU0gMzUyMDhkZAIDDw8WAh8CBQk1LzIxLzIwMThkZAIEDw8WAh8CBQFZZGQCYQ9kFgpmDw8WAh8CBQMxMDdkZAIBD2QWAmYPDxYEHwIFAjk1HwMFL34vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTEwNyZJbnNwTmJyPTI3ZGQCAg9kFgQCAQ8PFgIfAgUUQU1FUklDQU4gTEVHSU9OICMxMTNkZAIDDw8WAh8CBRwxMTQxIFBJTlNPTiBTVCBUQVJSQU5UIDM1MjE3ZGQCAw8PFgIfAgUINC82LzIwMThkZAIEDw8WAh8CBQFOZGQCYg9kFgpmDw8WAh8CBQQxMTkwZGQCAQ9kFgJmDw8WBB8CBQI5NB8DBTB+L0VIRlMvRlNTRGV0YWlscy5hc3B4P1Blcm1pdE5icj0xMTkwJkluc3BOYnI9MjRkZAICD2QWBAIBDw8WAh8CBRRBTUVSSUNBTiBMRUdJT04gIzEzN2RkAgMPDxYCHwIFHjUyMTAgVkFMTEVZIFJEIEZBSVJGSUVMRCAzNTA2NGRkAgMPDxYCHwIFCTEvMTgvMjAxOGRkAgQPDxYCHwIFAVlkZAJjD2QWCmYPDxYCHwIFBDY1ODVkZAIBD2QWAmYPDxYEHwIFAjg2HwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTY1ODUmSW5zcE5icj0yNGRkAgIPZBYEAgEPDxYCHwIFGUFNRVJJQ0FOIExFR0lPTiBQT1NUICMxMDdkZAIDDw8WAh8CBR04Mjk5IFJBSUxST0FEIEFWRSBMRUVEUyAzNTA5NGRkAgMPDxYCHwIFCTYvMjYvMjAxOGRkAgQPDxYCHwIFAU5kZAJkD2QWCmYPDxYCHwIFBDM5NThkZAIBD2QWAmYPDxYEHwIFAjkxHwMFMH4vRUhGUy9GU1NEZXRhaWxzLmFzcHg/UGVybWl0TmJyPTM5NTgmSW5zcE5icj0yN2RkAgIPZBYEAgEPDxYCHwIFGEFNRVJJQ0FOIExFR0lPTiBQT1NUICMyMmRkAgMPDxYCHwIFHjEyMDEgNFRIIEFWRSBTVyBCRVNTRU1FUiAzNTAyMmRkAgMPDxYCHwIFCTUvMTUvMjAxOGRkAgQPDxYCHwIFAU5kZAJlDw8WAh4HVmlzaWJsZWhkZBgBBR5jdGwwMCRNYWluQ29udGVudCRndkZvb2RTY29yZXMPPCsADAEIAgJkkgh6+ENwlC6xeyBwIiP6uJCGrW/IzYTf/ZgBWH2+ctE=',
                            '__VIEWSTATEGENERATOR' => '93ED4CD7',
                            '__EVENTVALIDATION'    => '/wEdAAlmnKzTfO+xh+qbhreLa0C3yl6TejLOUKUZ8Y9kTykFa5+I/HPZ86NEZcbXwR9jxA7msDRYuZWmPMEu0d+94igePYooppvH2PzZ2BoJoTrJKKJo+s/l+97RrfDL3JdcYysMT7kLOdxk9pikDqPtCWwjF5AOA1D09yc0cAmRHJBCCZX1wu7rL64lwdAute68Jh5rGjDaU5llTFWa1e/bMTmESCBNDv41wE2a6f1Vc0bZMw=='
                        ]
                    )
                ]
            ];

            $context = stream_context_create($opts);
        }

        $content = file_get_contents($url, false, $context);

        return str_get_html($content);
    }

    /**
     * Set error messages
     *
     * @param bool           $messages The error message(s) to add
     *
     * @return bool|mixed
     */
    private function _setErrors($messages = false) {
        if (is_bool($messages)) {
            $messages = false;
        } else if (!is_array($messages)) {
            $messages = [ $messages ];
        }

        $this->_errors = $messages;

        if (is_array($this->_errors)) {
            foreach ($this->_errors as $error) {
                error_log($error);
            }
        }

        return $this->_errors !== false;
    }

    /**
     * Set whether to use stdClass, JSON, or XML
     *
     * @param string|false $use
     *
     * @return void
     */
    private function _setUse($use) {
        if (is_string($use) && strtolower($use) === JcdhApi::OUTPUT_JSON) {
            $this->_useJson = true;
        } else if (is_string($use) && strtolower($use) === JcdhApi::OUTPUT_XML) {
            $this->_useXml = true;
        }
    }

    private function _splitNameAddress($string) {
        return preg_split('/\n|\r\n?/', $string);
    }

    public function getScores($types = self::TYPE_FOOD) {
        if (is_string($types)) {
            $types = explode(',', $types);
        }

        $scores = [];
        foreach ($types as $type) {
            $function = false;

            switch($type) {
                case self::TYPE_COMMUNAL_LIVING:
                    $function = 'getCommunalLivingScores';
                    break;
                case self::TYPE_FOOD:
                    $function = 'getFoodScores';
                    break;
                case self::TYPE_HOTEL:
                    $function = 'getHotelScores';
                    break;
                case self::TYPE_POOL:
                    $function = 'getPoolScores';
                    break;
                case self::TYPE_TANNING:
                    $function = 'getTanningScores';
                    break;
            }

            if ($function) {
                $scores[$type] = [];

                foreach ($this->_getLetters() as $letter) {
                    $moreScores = $this->$function($letter);

                    $scores[$types] = array_merge($scores[$types], $moreScores);
                }
            }
        }

        return $this->_processResults($scores);
    }

    public function getReport($permitNo) {
//        TODO: Should work for all types
        return $this->_getFoodReport($permitNo);
    }

    /**
     * Get errors
     *
     * @return bool|string[]
     */
    public function getErrors() {
        return $this->_errors;
    }

    /**
     * Check if there are any errors
     *
     * @return bool
     */
    public function hasErrors() {
        return !is_bool($this->_errors);
    }
}